version: "3.8"

services:
  auth-service:
    build:
      context: ./backend
    command: ["node", "AuthServer.js"]
    container_name: auth-serv
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  user-service:
    build:
      context: ./backend
    command: ["node", "UserServer.js"]
    container_name: user-serv
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "6000:6000"

  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on: 
      - auth-service
      - user-service
      - mongo
